name: manifests-deploy

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2 #install doctl and configure it to set kubectl context to doctl, pre-init with our token
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save abode
      - run: kubectl apply -f infra/kubernetes && kubectl apply -f infra/kubernetes-prod #apply our depl files, pointing to prod env

